options:
  nfs-common-options:
    type: string
    default: '{}'
    description: |
      CSV list of configuraiton options to push to /etc/default/nfs-common e.g.:
        'NEED_GSSD=yes,NEED_IDMAPD=yes'
